//! Viontin Macros — proc-macros for Domain-Driven Design support.
//!
//! # #[domain] Attribute
//!
//! Annotate a module to declare its domain boundaries:
//!
//! ```ignore
//! #[domain(name = "billing", allows = [order, payment])]
//! mod billing {
//!     pub struct Invoice;
//! }
//! ```
//!
//! This generates:
//! - A `Domain` definition with the given name and allowed dependencies
//! - Auto-registers the domain at runtime
//! - Optionally generates compile-time boundary checks

extern crate proc_macro;
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, ItemMod};

mod domain_attr;

use domain_attr::DomainAttr;

#[proc_macro_attribute]
pub fn domain(attr: TokenStream, item: TokenStream) -> TokenStream {
    let attr_config = parse_macro_input!(attr as DomainAttr);
    let mut module = parse_macro_input!(item as ItemMod);
    let domain_name = &attr_config.name;
    let allows = &attr_config.allows;
    let provides = &attr_config.provides;

    // Add domain definition inside the module
    let domain_def = quote! {
        /// Domain boundary definition — auto-generated by #[domain].
        pub mod __domain {
            use viontin::Domain;

            pub const DEFINITION: Domain = Domain::new(#domain_name)
                .allows(&[#(#allows),*])
                .provides(&[#(#provides),*]);
        }

        /// Register this domain at runtime.
        pub fn __register_domain() {
            viontin::register_domain(__domain::DEFINITION);
        }
    };

    // Generate the expanded output with domain definition injected
    let expanded = match &module.content {
        Some((_brace, _items)) => {
            // For braced modules, we emit the original module followed by registration code
            // The module itself stays unchanged; users call __register_domain() explicitly
            quote! {
                #module

                #domain_def
            }
        }
        None => {
            // File-based module
            quote! {
                #module

                #domain_def
            }
        }
    };

    expanded.into()
}

/// Generates a domain event struct with automatic domain tagging.
///
/// ```ignore
/// #[domain_event("billing")]
/// struct InvoicePaid {
///     invoice_id: String,
///     amount: f64,
/// }
/// ```
#[proc_macro_attribute]
pub fn domain_event(attr: TokenStream, item: TokenStream) -> TokenStream {
    let domain_lit = parse_macro_input!(attr as syn::LitStr);
    let item_struct = parse_macro_input!(item as syn::ItemStruct);
    let name = &item_struct.ident;
    let domain_str = domain_lit.value();

    let expanded = quote! {
        #[derive(Debug, Clone)]
        #item_struct

        impl viontin::fw::events::Event for #name {}

        impl viontin::domain::DomainEvent for #name {
            fn domain(&self) -> &str { #domain_str }
            fn event_name(&self) -> &str { stringify!(#name) }
        }
    };

    expanded.into()
}
